wd.sh
Replace $HOME to `~` when write and do reverse when read, thus wraps under home directory with same path can be reused on different platforms.
=> fix issue #31: add support to `~` expansion

wd.sh
Before listing out each key and value when running `wd list`, it will figure out the length of the longest key string and use that when formatting instead of always printing 20 characters. That will make sure that the arrows are aligned properly, even if the keys are longer than 20 characters long, and it will also use less than 20 characters if no key is that long.
The solution is a little bit dirty in that it will loop through the entries in `$WD_CONFIG` twice. Another solution could be to store the max in the config file for reference, and update this in `wd add` (or `add!`), but I figured this solution was safer and wouldn't break anything else in the process.
Also, I would love to write a test for this, but unfortunately I'm not too familiar with _shunit2_. I did, however, read …
=> Ensure aligned arrows in list command

test/tests.sh, wd.sh
Since `[ -d "$var" ]` can't recognise the `~` in `$var`, when do `wd clean`, directories which contain '~' will be deleted incorrectly.
=> fix wd clean to avoid mistaken delete

README.md
Hi,
I took the liberty of putting your original plugin version of `wd` [on the AUR] for easy access for us Arch people. Now, you may or may not be interested in this (seeing as you already have the [C port] in the AUR), but I thought I'd just suggest it nevertheless. For those that still want the Zsh plugin version of `wd` and aren't using oh-my-zsh, I think this could be nice to have.
[on the AUR]: https://aur.archlinux.org/packages/zsh-plugin-wd-git/
[C port]: https://github.com/mfaerevaag/wd-c/
Also, if you'd like to maintain the AUR package together with your C port package on the AUR, please feel free to say so, I'm more than happy to transfer it over to you.
Thanks for making our lives easier through `wd`! :smile:
=> Add note about installing through the AUR

_wd.sh, wd.sh
With this we have path completion after warp point, so typing
wd foo <tab>
will list all subfolders of the foo wp's target dir. Only folders are
shown. It's a smooth completion because typing <tab> twice after the
warp points name gives the completion.
=> warp directly to subdir of warp point

test/tests.sh, wd.sh
This prevents the check to prevent overriding an existing warp point
from being inhibited when no argument is provided and the warp point
name defaults to the basename of the current directory.
=> Don't overwrite existing point when arg omitted

wd.sh
Fixes #47. Sort of. You still can't add a warp point with spaces, but at least you get the right error message now.
=> Eliminate wordsplitting when getting basename

README.md, _wd.sh, test/tests.sh, wd.sh
With this PR
* `WD_CONFIG` will no longer be overwritten, and can be set by the user, to specify a custom location for the warp file
* the completion uses `WD_CONFIG` to determine the warp file
Issue #52
=> Add support for customizable warp file

wd.sh
zsh supports global aliases, which are expanded "anywhere", including
case labels, potentially causing unwanted behaviors or parsing errors.
I have a "NO" (No Output) alias which is "NO: globally aliased to > /dev/null 2>&1".
Because the wd.sh script is sourced from an interactive shell, this alias was present
and was causing a parsing error.
=> Add quotes around case labels

wd.sh
* Copy and delete in two steps in order to preserve symlinks
* Use mktemp to generate temporary file location
=> Save fixes - Preserve symlinks and improved tmpfile generation

_wd.sh, wd.sh
I've integrated the export as additional command into `wd.sh`.
- `wd export` needs to be called from `.zshrc` (or the oh-my-zsh plugin file)
- seems this needs to be called with `.` (source) for the hash function to work (`. wd export`)
- entries are added unless `WD_SKIP_EXPORT` is set
- new entries are exported (`wd add`)
- removed entries are currently ignored until next shell is opened (it is possible to empty the hash table with `hash -d -r` and regenerate but that might affect other custom entries)
- i haven't added that yet because i'm not sure if that might affect some users (removes all custom entries - shouldn't be a problem though)
I'm not too sure about this solution since sourcing the `wd.sh` file in `.zshrc` gives a little delay (though not much) so i'm open for ideas. …
=> added static named directories export

_wd.sh
fixes #67 
new behaviour is that tab doesn't show any prompts or lists if the warp point is not found, which seems intuitive to me, but might not be as friendly as I think it is
=> prevent subdir autocompletion for non-existent warp points

wd.sh
Fixes #65 
The name `o`, chosen initially, could be used as an alias by some user, which would break the plugin. Making the variable local and prefixed makes sure that the name is going to be somewhat unique :)
=> Iterate CLI args with a local, prefixed variable

README.md, wd.plugin.zsh
In order to be able to use the plugin with [Antigen](https://github.com/zsh-users/antigen)/[Antibody](https://github.com/getantibody/antibody), there should be a `.plugin.zsh` file (or similar), where the function for the plugin is defined. One could use the ohmyzsh version, but it is severely outdated.
This PR adds the `wd.plugin.zsh` file and updates the README with install instructions for Antibody and Antigen as well as some fixes to the formatting and grammar of README.
=> Add .plugin.zsh file and update README.md

wd.sh
If a warp directory had whitespace in the path (e.g. `/home/atk/Git Projects/wd`), then the `hash` function on line 346 would throw a warning that it wasn't being given a valid directory (the warp still worked). This was because the for loop splits on any whitespace, so having a space in a path name would bugger everything and the single warp point would be split at every whitespace. To fix this, I changed the loop to use a `read`, which splits on newlines only, thus allowing everything to work as intended.
Running the tests for me failed epicly, though from lightly using my modified version I'm honestly not sure why. Test output:
```test_empty_config
test_simple_add_remove
ASSERT:should successfully add wp 'foo'
ASSERT:should have 1 wps expected:<1> but was:<0>
ASSERT:wp 'foo' should …
```
=> Fix wd_export_static_named_directories() throwing warnings

wd.sh
Will close #16, allows removal of multiple warp points in one go
No tests for this yet, may work out how to write those in due course.
Only one of the commits coming through is relevant for the change - 7fb1383. The other is simply as a result of me updating my fork, so you should be able to rebase my patch onto your master without needing both commits.
Here's a patch file if you'd prefer
```
---
wd.sh | 5 ++++-
1 file changed, 4 insertions(+), 1 deletion(-)
diff --git a/wd.sh b/wd.sh
index 802ed10..f073897 100755
--- a/wd.sh
+++ b/wd.sh
@@ -430,7 +430,10 @@ else
break
;;
"-r"|"--remove"|"rm")
-                wd_remove $2
+                # Loop over all arguments after "rm", separated by whitespace
+                for pointname in "${@:2}" ; do
+                    wd_remove $pointname …
```
=> Multi remove

wd.sh
When using `wd list` or `wd <TAB>`, which shows the list of warp points, I find it incredibly helpful to have the warp points alphabetized.
Because I believe what is convenient for me is right for everyone else, I did not implement a toggle for whether to enable this sort or not. 😉 I'm happy to implement that if you think it makes sense.
=> Alphabetize warp points when they are added

wd.sh
The short commands `cp` and `rm` are often aliased to `cp -i` and `rm -i` to
avoid accidental overwrites and deletes, but this breaks the behavior of wd.
=> Use file tools with full path to avoid capture by alias

wd.sh
This effectively makes exporting static named directories off by default, stopping `wd` from messing with path names in terminal prompts
Closes #85
=> Change WD_SKIP_EXPORT to WD_EXPORT

wd.sh
Fixes issue identified after merging PR #83
`wd rm` now correctly tries to remove a point with the name of the current directory
I also moved the looping logic to the `wd_remove` function itself as I believe it's better there. See the difference between the first and second commit for the two possible solutions
=> Multi remove regression fix

test/tests.sh, wd.sh
Essentially I used the [`shellcheck`](https://www.shellcheck.net/) tool to pick over `wd` and try and improve the code style, particularly robustness against whitespace. This PR therefore will solve #89.
It is worth noting `shellcheck` does not natively support zsh so I ran it in bash mode and simply didn't touch anything too technical in syntax which could have been zsh specific. Most of the changes therefore are just adding loads of "quotations" all over the place.
=> Increase compliance with `shellcheck` best practices

test/tests.sh, wd.1, wd.sh
Will close #15, this PR adds a `-f` and `--force` option which replaces the `add!` and `clean!` notation
~~Making this PR a draft as it will probably break the tests and I haven't looked into fixing them yet~~
I think I've updated the documentation in the man and the `--help`, but a once over would be appreciated.
I'm also not overly sure how inkeeping my changes are with the code style of the existing work, I have limited experience coding in zsh as I mostly stick to sh for what I need.
As per my other PR, 14d884a doesn't hold any relevant changes and could be left out when merging, I just needed to get my fork up to date
=> Use a force flag instead of !

test/tests.sh, wd.sh
Will close #59 
While a semi-destructive solution to the problem, as it removes functionality to the user, allowing slashes in warp names would prevent a feature like #66 being implemented, which I think has more value than a niche of people wanting slashes in warp point names.
However, because this isn't an 'everyone wins' situation, I'm making a PR and asking for input, from ideally the issue opener @joncalhoun and another maintainer
Tests have been added for this new prevention
=> Prevent usage of slashes in warp points

test/tests.sh, wd.sh
Will close #91 
Updated test logic to do the same
Maybe it'd be better to control if an absolute path is given or not through a flag, instead of just changing the default behaviour. Thoughts?
=> Change `wd path` to give absolute path

test/tests.sh, wd.sh
A warp point such as "list" can be set through "wd add list", but then
"wd list" does not chdir to it, but rather invokes the list command. To
prevent confusion, such warp points names should not be allowed.
=> disallow warp point names that clash with commands

test/tests.sh
As noticed in #105, MacOS `wc -l` produces extra whitespace padding at
the front of the word count.  This makes it so that running the tests on
MacOS produces false negatives.
The fix here is to add a new function that calls `wc -l` then uses `sed`
to strip out the extra whitespace.  This is only used in the tests.
After running this on a MacOS machine, all tests pass as expected.
Note: this doesn't address the bug listed in #105.   This just fixes the problem
with running the tests.
=> Fix tests to run correctly using MacOS `wc`

README.md
We recently listed wd on [Fig Plugin Store](https://fig.io/plugins), so we'd love to have Fig listed as a download method on your readme. We have over 100k users that will benefit from this. 
Thanks so much and please let me know if you have any questions!
=> Add Fig as an installation method

wd.sh
Fix the warp points not complete issue:
```zsh
~/demo:cpp % wd add democpp
* Warp point added
```
```zsh
~/demo:cpp % wd list
* All warp points:
democpp  ->  ~/demo
```
```zsh
~/demo:cpp % wd list
* All warp points:
democpp  ->  ~/demo:cpp
```
=> Fix "wd list" error if path contains symbol ":"

test/tests.sh
While we cannot test the wrong behaviour (~-target not shown) in a meaningful way, we certainly can test for the correct one.
=> Add test for ~-containing targets

wd.sh
while wd is running, that is.
I have additional problems with variable expansion related to ~, e.g. in prompts and terminal titles. I propose this change, because ~ globbing is done in other places as well. Tests pass.
=> Disable extglob completely

wd.sh
Hi!
I am the maintainer of Oh My Zsh, and we bumped into [this issue](https://github.com/ohmyzsh/ohmyzsh/issues/12017) that I could reproduce. It seems that the syntax `[[ 1 ]]` (or any number actually) is invalid in zsh <5.0.6.
[We already fixed it](https://github.com/ohmyzsh/ohmyzsh/pull/12019), here you have the changes.
Thanks for your work!
=> fix: extend compatibility to zsh <5.0.6

README.md
This PR adds a section to the installation instructions for installing the current version of `wd` with [home manager](https://github.com/nix-community/home-manager). Tested this with [my own setup](https://github.com/zimeg/.DOTFILES/blob/e80adb44650d0dde4314e1c14e6f4909ea7a4fa6/nix/home.nix#L33-L43) and it seems to be working well!
The `rev` and `sha256` fields are tied to a specific release tag and might need updating with new releases. Or it could just be reference for the format. Using the latest tag with an incorrect hash will error with the correct hash displayed, so it's not too bad to figure out the new hash.
<details>
<summary>
But a more formal approach might use `nix-prefetch` to find the actual hash for the version.
</summary>
```sh
$ nix-prefetch-git …
```
=> Include instructions for installing with home manager

README.md, _wd.sh, test/tests.sh, wd.1, wd.plugin.zsh, wd.sh
Added new function to allow you to add a bunch of directories quickly without needing to cd to them first.
addcd (path)        Adds a path to your warp points with the directory's name
addcd (path) (point) Adds a path to your warp points with a custom name
=> Added ability to add warp points to other directories

wd.sh
Hi,
When I had added the delete functionality I accidently broke the browse functionality. Oops!
This fixes it.
=> Fixed regression errors

.github/workflows/release.yml
👋 Howdy! This PR bumps version numbers and updates a date before creating a new release via GitHub Action. Motivation: https://github.com/mfaerevaag/wd/commit/c7a72236718712fc8fde2fb7cdb4891197de1967#comments
Some testing was done on [this fork](https://github.com/zimeg/wd). Interesting commits and other things to note might include:
- 760d84e60daf533dc7634427f964ab252f3c79d5: This exact commit. No differences from this PR except that it's merged to `master`.
- ec4cde58da16910f90fdd32d09705d664561173d: An example PR. Changes must be made through PR to be included in release notes automatically. Edits to these notes after are of course possible. New contributors will be included too!
- 72388003378f6c285027adcdb78ce0733f4fb315: Automated changes. The `--version` variable is updated, and the …
=> ci(release): bump versions to the latest release

README.md, wd.plugin.zsh
The ctrl-b key is used for fundamental navigation in default emacs-style zsh, and it isn't clear that wd is rebinding it.
Instead of guessing at what keybind would be suited, it's just removed and the docs are made clearer.
See #133
=> Remove omz plugin bindkey for browse

install.sh, test/tests.sh, wd.plugin.zsh, wd.sh
This PR gathers the interpreted `zsh` path using the `env` program to fix #135 and allow changed paths to the `zsh` program.
The `test/tests.sh` file was also updated to run these tests, but the files in `test/shunit2/*` are left as-is which seems to work fine! Tests pass with this change 🎉  
Test these updates with a package manager of choice and these commands:
```zsh
$ wd
...
$ wd --version
wd version 0.8.0
```
Also check that warps and other commands continue to warp:
```zsh
$ wd list
...
$ cd
$ pwd
$ wd [example]  # Perform a warp
$ pwd
```
This seems to work on the following setups, but I'm uncertain about other platforms - all other testing would be super appreciated:
- zsh 5.9 (aarch64-apple-darwin23.6.0)
- zsh 5.9 (x86_64-pc-linux-gnu)
Also open to rebasing commits if needed, …
=> fix: find the path to zsh with the env program

README.md, test/tests.sh, wd.1, wd.sh
This PR returns the `$WD_EXIT_CODE` to whatever it might be set to when this program completes for all cases, not just the testing done in debug mode, to fix #137.
With the changes of this branch, the following commands continue to **warp** or exit with the error code:
```zsh
$ wd list
...
$ cd
$ wd [example]
$ echo $?
0
$ pwd
$ wd bogus
* Unknown warp point 'bogus'
$ echo $?
1
```
A `return` is preferred to `exit` to avoid quitting the sourced shell session, but I'm not certain about this change so thoughts or more testing for this would be nice!
I've tested both errors and successful warps on the following setups, and feel mostly confident with these:
- zsh 5.9 (aarch64-apple-darwin23.6.0)
- zsh 5.9 (x86_64-pc-linux-gnu)
The unit testing asserts also seem to have been working as …
=> fix: return erroring exit codes with the set exit value

wd.sh
Resolves #114 
use a local variable within `wd_show` to check if we are in a warp point directory or not
```
❯ wd list
* All warp points:
control-deploy  ->  ~/git/ose-automation-puppet/control-deploy
dope  ->  ~/git/one-thd/dope
ls-base  ->  ~/git/one-thd/locksmith
V6YNJVV4QCMBP in ~/git
❯ wd dope
V6YNJVV4QCMBP in git/one-thd/dope
❯ wd show
* 1 warp point(s) to current directory: dope
V6YNJVV4QCMBP in git/one-thd/dope
❯ cd ..
V6YNJVV4QCMBP in ~/git/one-thd
❯ wd show
* No warp point to ~/git/one-thd
V6YNJVV4QCMBP in ~/git/one-thd
❯ echo $PWD
/Users/jxb2016/git/one-thd
```
=> don't clobber PWD in wd_show

test/tests.sh, wd.sh
:wave: Hello! This PR restores the initial value of the `WD_CONFIG` environment variable after the `--config` flag is used. It hopes to fix #140.
Also included is an update to `source` the tested `wd` so changed variables and directories are shared between different testing commands.
The following steps have commands that use different configuration files, but the last commands use a configuration from the option above which might be an unexpected part!
1. List outputs from the current `WD_CONFIG` value. This could be using a default that might have a few points included:
```zsh
$ echo $WD_CONFIG
/home/user/.warprc
$ cat $WD_CONFIG
...
$ wd list
...
```
2. List points from a configuration that might not exist. This might list nothing:
```zsh
$ wd --config /tmp/points list
...
```
3. …
=> fix: avoid overwriting the configuration file environment variable

test/tests.sh, wd.sh
:wave: 🤠 This PR updates the exit code with the returned value from `cd` in the `wd_warp` function to fix #142 and break chained commands if nested directories don't exist.
With this change the exit code is set to `1` when a missing nested warp point is provided:
```zsh
$ wd home unknown
wd_warp:cd:19: no such file or directory: /home/user/unknown
$ echo $?
1
```
Chained commands also break once the missing nested warp point is reached:
```zsh
$ wd home unknown && ./setup.sh
wd_warp:cd:19: no such file or directory: /home/user/unknown
```
To test the changes with this branch checked out, the following commands might be useful ✨ 
1. Attempt to warp to unknown nested warp points:
```zsh
$ cd
$ wd add home
$ wd home unknown
wd_warp:cd:19: no such file or directory: /home/user/unknown
$ echo …
```
=> fix: set the exit code to the return of cd for the warp function

_wd.sh, wd.1, wd.sh
- Closes #147 
The `open` command is natively available on MacOS. On Linux, `xdg-open` should be widely available, although some distros (Ubuntu?) seem to alias it as `open`. I check for presence of either command, rather than relying on the `$OSTYPE` variable. I hope it's more reliable.
The ZSH autocompletion works fine - tested by copying the new `_wd.sh` file into my oh-my-zsh plugins and running new zsh.
I didn't add any tests, because I don't know how should I test that the desktop environment opened an application.
> [!NOTE]
> I'm on a mac. Someone should test it on linux!
=> Implement `open` command

README.md
👋 Hello! This PR updates the installation instructions for Home Manager to use the latest `wd` package available.
Follows #117 📚 
Original documentation recommended fetching an upstream source because the Home Manager `zsh.plugins` settings weren't finding completions which IMO wouldn't have been good to suggest... 🤖 
A recent update to Home Manager added the `completions` option for plugins which unlocks both autocomplete and manual pages! 👾 
- `zsh-wd` on `nixpkgs`: https://search.nixos.org/packages?channel=unstable&query=zsh-wd
- `zsh.plugins`: https://nix-community.github.io/home-manager/options.xhtml#opt-programs.zsh.plugins
- `completions`: https://github.com/nix-community/home-manager/pull/7197
=> docs: recommend latest plugin version with home manager installation
